# Check Lua Formatting
name: Check Lua Formatting
on: push

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Stylua Check
        uses: nebularg/actions-luacheck@v1
